name: Swift

on: 
  push:
    tags:        
      - *.*

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build
      run: swift build -c release
    - name: Test Binary
      run: ./.build/release/EditXCProject

    - name: GitHub Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          .build/release/EditXCProject